// Most of the following chuncks of code are my way of switching the costume of the Active Talker sprite. There is probably a more effective way of doing this. But this is good enough for me.
// This is a function script that changes the sprite of the active talker to Daniel's Beat up texture.
function Active_talker_set_Beat_Up_Daniel () {
    sprites.destroy(Active_Talker)
    Active_Talker = sprites.create(assets.image`Daniel damaged Armoured 1`, SpriteKind.Player)
    Active_Talker.setPosition(110, 58)
    Active_Talker.setScale(3, ScaleAnchor.Middle)
}
// This is a function script that changes the sprite of the active talker to the player's texture.
function Active_talker_set_Rookie () {
    sprites.destroy(Active_Talker)
    Active_Talker = sprites.create(assets.image`Rookie Armoured 1`, SpriteKind.Player)
    Active_Talker.setPosition(110, 58)
    Active_Talker.setScale(3, ScaleAnchor.Middle)
}
// This is a function script that changes the sprite of the active talker to Evil Daniel's texture.
function Active_talker_set_Daniel_Grain () {
    sprites.destroy(Active_Talker)
    Active_Talker = sprites.create(assets.image`Evil Daniel Armoured 1`, SpriteKind.Player)
    Active_Talker.setPosition(110, 58)
    Active_Talker.setScale(3, ScaleAnchor.Middle)
}
// This is a function script that changes the sprite of the active talker to Will's texture.
function Active_talker_set_Will () {
    sprites.destroy(Active_Talker)
    Active_Talker = sprites.create(assets.image`Will Armoured 1`, SpriteKind.Player)
    Active_Talker.setPosition(110, 58)
    Active_Talker.setScale(3, ScaleAnchor.Middle)
}
// This is a function script that changes the sprite of the active talker to Louis' texture.
function Active_talker_set_Louis_Dead () {
    sprites.destroy(Active_Talker)
    Active_Talker = sprites.create(assets.image`Louis Killed 1`, SpriteKind.Player)
    Active_Talker.setPosition(110, 58)
    Active_Talker.setScale(3, ScaleAnchor.Middle)
}
// This is a function script that changes the sprite of the active talker to Dom's texture.
function Active_talker_set_Alex () {
    sprites.destroy(Active_Talker)
    Active_Talker = sprites.create(assets.image`Alex Armoured 1`, SpriteKind.Player)
    Active_Talker.setPosition(110, 58)
    Active_Talker.setScale(3, ScaleAnchor.Middle)
}
// This is a function script that changes the sprite of the active talker to Ruby's texture.
function Active_talker_set_Ruby () {
    sprites.destroy(Active_Talker)
    Active_Talker = sprites.create(assets.image`Ruby Armoured 2`, SpriteKind.Player)
    Active_Talker.setPosition(110, 58)
    Active_Talker.setScale(3, ScaleAnchor.Middle)
}
controller.right.onEvent(ControllerButtonEvent.Pressed, function () {
    story.clearAllText()
})
// Most of the following chuncks of code are my way of switching the costume of the Active Talker sprite. There is probably a more effective way of doing this. But this is good enough for me.
// This is a function script that changes the sprite of the active talker to Daniel's kidnapped texture.
function Active_talker_set_Kidnapped_Daniel () {
    sprites.destroy(Active_Talker)
    Active_Talker = sprites.create(assets.image`Daniel damaged Armoured 0`, SpriteKind.Player)
    Active_Talker.setPosition(110, 58)
    Active_Talker.setScale(3, ScaleAnchor.Middle)
}
// This is a function script that changes the sprite of the active talker to Louis' texture.
function Active_talker_set_Louis () {
    sprites.destroy(Active_Talker)
    Active_Talker = sprites.create(assets.image`Louis Armoured 1`, SpriteKind.Player)
    Active_Talker.setPosition(110, 58)
    Active_Talker.setScale(3, ScaleAnchor.Middle)
}
// Most of the following chuncks of code are my way of switching the costume of the Active Talker sprite. There is probably a more effective way of doing this. But this is good enough for me.
// This is a function script that changes the sprite of the active talker to Daniel's texture.
function Active_talker_set_Disguised_Daniel () {
    sprites.destroy(Active_Talker)
    Active_Talker = sprites.create(assets.image`Daniel Grain Armoured 1`, SpriteKind.Player)
    Active_Talker.setPosition(110, 58)
    Active_Talker.setScale(3, ScaleAnchor.Middle)
}
// This clears the active talker form the screen for when a completely blank screen is needed. such as during transitions.
function Active_talker_clear () {
    sprites.destroy(Active_Talker)
}
// Most of the following chuncks of code are my way of switching the costume of the Active Talker sprite. There is probably a more effective way of doing this. But this is good enough for me.
// This is a function script that changes the sprite of the active talker to Daniel's Beat up texture.
function Active_talker_set_Dead_daneil () {
    sprites.destroy(Active_Talker)
    Active_Talker = sprites.create(assets.image`Daniel dead 1`, SpriteKind.Player)
    Active_Talker.setPosition(110, 58)
    Active_Talker.setScale(3, ScaleAnchor.Middle)
}
// Most of the following chuncks of code are my way of switching the costume of the Active Talker sprite. There is probably a more effective way of doing this. But this is good enough for me.
// This is a function script that changes the sprite of the active talker to Daniel's kidnapped texture.
function Active_talker_set_Battle_damaged_Daniel () {
    sprites.destroy(Active_Talker)
    Active_Talker = sprites.create(assets.image`Daniel damaged Armoured 2`, SpriteKind.Player)
    Active_Talker.setPosition(110, 58)
    Active_Talker.setScale(3, ScaleAnchor.Middle)
}
let Active_Talker: Sprite = null
let Gender = ""
let Version_Number = textsprite.create("Beta 0.2", 15, 13)
let Version_Code = textsprite.create("25W26C")
sprites.destroy(Version_Code)
Version_Number.setPosition(32, 10)
// This contains the first set of screens that show the title of the game and who made it, before it fades into the main menu
let i = textsprite.create("Daniel Good Presents:")
i.setPosition(90, 59)
pause(2000)
i.setText("Bushrangers")
pause(1000)
sprites.destroy(i, effects.halo, 500)
pause(1000)
music.setVolume(50)
music.play(music.createSong(assets.song`Menu 1`), music.PlaybackMode.LoopingInBackground)
scene.setBackgroundImage(assets.image`Earth`)
game.setDialogCursor(assets.image`Diologue select Icon`)
game.splash("Press Space to Start", "Right arrow to skip text")
scene.setBackgroundImage(assets.image`Background`)
music.stopAllSounds()
music.setVolume(100)
Active_talker_set_Disguised_Daniel()
story.setSoundEnabled(true)
story.printCharacterText("Hi. Welcome to Blue Team! My name's Daniel and I'm the commander of this Squad.", "Daniel")
story.printCharacterText("If You Follow Me, I can introduce you to the team.", "Daniel")
story.printCharacterText("So, uhhh. I may or may not have forgotten your name. Could you remind me real quick?", "Daniel")
let UserName = game.askForString("What's Your name?")
// This checks for any slurs that may be put into the name. I haven't written all the slurs I can think of but here were the main ones that came up when I asked people to put a name in during testing.
if (UserName == "Nigger" || (UserName == "Fuck" || (UserName == "Shit" || (UserName == "Osama" || false)))) {
    story.printCharacterText("Hmmm. I don't think " + ("" + UserName) + " Is appropriate for this environment. Restart", "Daniel")
    pause(1000)
    game.reset()
}
story.printCharacterText("Hey! " + UserName + "! I knew it was something like that... definitely...", "Daniel")
story.printCharacterText("Alright, Let's introduce you to everyone.", "Daniel")
story.showPlayerChoices("Ok.", "Do I have to?")
if (story.checkLastAnswer("Do I have to?")) {
    story.printCharacterText("Well, I mean. The game won't really make sense if you don't know anyone.", "Daniel")
    story.printCharacterText("Actually. I won't have a Game at all.", "Daniel")
    story.printCharacterText("I guess that means we just have to stare at each other uncomfortably.", "Daniel")
    pause(2000)
    story.printCharacterText("I've never had a Rookie on the team before.", "Daniel")
    story.printCharacterText("Are you all this weird?", "Daniel")
    story.showPlayerChoices("Yes.", "I don't know. I just work here.", "No.")
    pause(2000)
    story.showPlayerChoices("This Is awkward.", "You have great eyes.")
    if (story.checkLastAnswer("This Is awkward.")) {
        story.printCharacterText("Yeah. It really is.", "Daniel")
        story.printCharacterText("I think you should just restart the game at this point.", "Daniel")
        game.setGameOverEffect(false, effects.starField)
        game.gameOver(false)
        game.setGameOverMessage(false, "Awkward Ending!")
    } else {
        story.printCharacterText("...", "Daniel")
        story.printCharacterText("Um", "Daniel")
        story.printCharacterText("Thanks?", "Daniel")
        story.printCharacterText("I Guess?", "Daniel")
        story.printCharacterText("I think you should just restart the game at this point.", "Daniel")
        game.setGameOverEffect(false, effects.starField)
        game.gameOver(false)
        game.setGameOverMessage(false, "Awkward Ending!")
    }
} else {
    story.printCharacterText("Great! First up is Blue 2. Will B-064.", "Daniel")
    story.printCharacterText("Will is the marksman of our team. He can hit just about anything with his rifle. ", "Daniel")
    story.printCharacterText("Hey Will!", "Daniel")
    Active_talker_set_Will()
    story.printCharacterText("Yeah? What?", "Will")
    story.printCharacterText("Oh!, Is this our new number 6?", "Will")
    Active_talker_set_Disguised_Daniel()
    story.printCharacterText("Yep. His? Her? Wait, What gender are You?", "Will")
    story.showPlayerChoices("Male", "Female", "Attack Helicopter", "Other")
    if (story.getLastAnswer() == "Male") {
        Gender = story.getLastAnswer()
    } else if (story.getLastAnswer() == "Female") {
        Gender = story.getLastAnswer()
    } else if (story.getLastAnswer() == "Attack Helicopter") {
        Gender = story.getLastAnswer()
    } else {
        Gender = game.askForString("What do you Identify As?", 24)
    }
    story.printCharacterText("Right... so " + Gender + "'s Name is " + UserName, "Daniel")
    story.printCharacterText("" + UserName + " Was assigned to our team as a Rookie.", "Daniel")
    story.printCharacterText("Alright. So that was Will. Now lets move on.", "Daniel")
    story.printCharacterText("Next We Have Blue 3. Ruby B-115", "Daniel")
    story.printCharacterText("Ruby is by far the fastest one on our team. She can have a bit of a short fuse, but she's harmless if you're on the right side.", "Daniel")
    story.printCharacterText("Ruby!", "Daniel")
    Active_talker_set_Ruby()
    story.printCharacterText("What?", "Ruby")
    Active_talker_set_Disguised_Daniel()
    story.printCharacterText("This is our new Rookie", "Daniel")
    Active_talker_set_Ruby()
    story.printCharacterText("Oh! Hi!", "Ruby")
    story.printCharacterText("My name's Ruby, and you are?...", "Ruby")
    story.showPlayerChoices(UserName, "The new Rookie.")
    if (story.checkLastAnswer("The new Rookie.")) {
        story.printCharacterText("Yeah, I know but what's your-", "Ruby")
        story.printCharacterText("Never mind.", "Ruby")
    } else {
        story.printCharacterText("" + UserName + "! Nice to meet you.", "Ruby")
    }
    story.printCharacterText("Alright. Well that's that. I should probably get back to training. Catch you later?", "Ruby")
    Active_talker_set_Disguised_Daniel()
    story.printCharacterText("Nearly done! We've got two more people to go!", "Daniel")
    story.printCharacterText("Next is Blue 4. Louis B-820.", "Daniel")
    story.printCharacterText("Louis is the pilot. He is the one who gets us in and out of our missions.", "Daniel")
    story.printCharacterText("You usually find him tinkering with his bird.", "Daniel")
    story.printCharacterText("But he can get a bit-", "Daniel")
    scene.cameraShake(7, 500)
    story.printCharacterText("SHIT!", "Louis")
    Active_talker_set_Louis()
    story.printCharacterText("F#CKING SHIT!", "Louis")
    Active_talker_set_Disguised_Daniel()
    story.printCharacterText("Non Family-Friendly...", "Daniel")
    story.printCharacterText("Hey! Louis!", "Daniel")
    Active_talker_set_Louis()
    story.printCharacterText("What?", "Louis")
    Active_talker_set_Disguised_Daniel()
    story.printCharacterText("Our new Rookie's here, try and keep it PG and not use such a... colourful set of words please?", "Daniel")
    Active_talker_set_Louis()
    story.printCharacterText("Fine", "Louis")
    story.printCharacterText("Hi, How's it going?", "Louis")
    story.showPlayerChoices("Good.", "What happened back there?")
    if (story.checkLastAnswer("What happened back there?")) {
        story.printCharacterText("A fuel tank combusted while it was active.", "Louis")
    }
    scene.cameraShake(5, 500)
    story.printCharacterText("BANG!", "")
    story.printCharacterText("Shit.", "Louis")
    story.printCharacterText("I gotta go fix that.", "Louis")
    Active_talker_set_Disguised_Daniel()
    story.printCharacterText("So Yeah. That's Louis...", "Daniel")
    story.printCharacterText("Anyway, Last one.", "Daniel")
    story.printCharacterText("Alex B-517", "Daniel")
    story.printCharacterText("The Demo man.", "Daniel")
    story.printCharacterText("He's the one that carries all of our ordnance. Explosives, heavy weapons, Spare ammunition, the works.", "Daniel")
    Active_talker_set_Alex()
    story.printCharacterText("Hey! You must be the new rookie! ", "Alex")
    story.printCharacterText("Got a question for ya.", "Alex")
    story.printCharacterText("How many kilos of explosives would I need to blow this facility sky high?", "Alex")
    story.showPlayerChoices("10", "50", "100", "Why do you ask?")
    if (story.checkLastAnswer("Why do you ask?")) {
        story.printCharacterText("No reason.", "Alex")
        story.printCharacterText("Ya'know, higher ups want a failsafe if this facility falls into the wrong hands.", "Alex")
        story.printCharacterText("Nothing too important", "Alex")
    }
    story.printCharacterText("Alright, thanks for the help. I gotta go now.", "Alex")
    story.printCharacterText("BANG!", "")
    scene.cameraShake(4, 500)
    Active_talker_set_Louis()
    story.printCharacterText("F#CK! ALEX! STOP LEAVING THE THERMAL CORD NEAR THE THRUSTERS!", "Louis")
    Active_talker_set_Disguised_Daniel()
    story.printCharacterText("Yikes. That does not sound good. We should go check it out", "Daniel")
    story.printCharacterText("Louis!? What happened?", "Daniel")
    Active_talker_set_Louis()
    story.printCharacterText("Alex left his goddamn explosive thermal cord behind my thruster.", "Louis")
    story.printCharacterText("I activated the thrusters to test that they work, but it activates Alex's thermal cord and nearly blows the ship to the ninth realm!", "Louis")
    Active_talker_set_Alex()
    story.printCharacterText("What did I do?", "Alex")
    Active_talker_set_Louis()
    story.printCharacterText("You nearly killed me!", "Louis")
    story.printCharacterText("You left your thermal cord near my thrusters during testing!", "Louis")
    Active_talker_set_Alex()
    story.printCharacterText("WHAT!? NO! My thermal cord is right here!", "Alex")
    story.printCharacterText("It was right here...", "Alex")
    Active_talker_set_Louis()
    story.printCharacterText("I don't see it.", "Louis")
    Active_talker_set_Alex()
    story.printCharacterText("I swear! I had it on me!", "Alex")
    Active_talker_set_Disguised_Daniel()
    story.printCharacterText("Alright! Chill.", "Daniel")
    story.printCharacterText("We'll have a meeting and discuss some problems.", "Daniel")
    story.printCharacterText("It will also be a good chance to show " + UserName + " how our team functions.", "Daniel")
    Active_talker_clear()
    game.splash("The Meeting", "Spacebar to continue")
    Active_talker_set_Disguised_Daniel()
    story.printCharacterText("Ok.", "Daniel")
    story.printCharacterText("You have all been called here to discuss some issues that have been occouring.", "Daniel")
    story.printCharacterText("Now, I have received word from command that someone on our team has been working for the enemy.", "Daniel")
    story.printCharacterText("Before we start pointing fingers, we should all do some investigating to see if we can get a lead.", "Daniel")
    story.showPlayerChoices("*Stay Quiet*", "Blame Alex", "Blame Daniel", "Blame Will", "Blame Ruby")
    if (story.checkLastAnswer("Blame Daniel")) {
        story.printCharacterText("...", "Daniel")
        story.printCharacterText("What?", "Daniel")
        Active_talker_clear()
        game.splash("After the Meeting", "Press space to continue")
        Active_talker_set_Disguised_Daniel()
        story.printCharacterText("Hmm. Didn't think the Rookie would catch onto me this early.", "Daniel")
        Active_talker_set_Daniel_Grain()
        story.printCharacterText("You know... It's really unfortunate that it has to end this way.", "Daniel")
        story.printCharacterText("I really enjoyed your time on the team.", "Daniel")
        story.printCharacterText("But the truth is...", "Daniel")
        story.printCharacterText("The game was rigged from the start.", "Daniel")
        Active_talker_clear()
        game.setGameOverEffect(false, effects.melt)
        game.setGameOverMessage(false, "You Died.")
        game.gameOver(false)
    } else if (story.checkLastAnswer("Blame Alex")) {
        Active_talker_set_Alex()
        story.printCharacterText("Why me?", "Alex")
        story.printCharacterText("Hmph.", "Alex")
        story.printCharacterText("I didn't do anything", "Alex")
        Active_talker_clear()
        game.splash("After the Meeting", "Press space to continue")
        Active_talker_set_Disguised_Daniel()
        story.printCharacterText("Hey, I think you're on the right track with Alex.", "Daniel")
        story.printCharacterText("But it would have been better if you didn't call him out.", "Daniel")
        story.printCharacterText("Now he knows we're onto him, he's going to be a lot sneakier.", "Daniel")
    } else if (story.checkLastAnswer("Blame Will") || story.checkLastAnswer("Blame Ruby")) {
        Active_talker_set_Disguised_Daniel()
        story.printCharacterText("Umm... Let's get some evidence first.", "Daniel")
        game.splash("After the Meeting", "Press Space to continue")
    } else {
        Active_talker_set_Disguised_Daniel()
        game.splash("After the Meeting", "Press Space to continue")
    }
    Active_talker_set_Disguised_Daniel()
    story.printCharacterText("Alright! let's Scooby Doo this shit!", "Daniel")
    story.printCharacterText("Ok, " + UserName + ", I think it might be Alex.")
    story.printCharacterText("But we need proof.", "Daniel")
    story.printCharacterText("This is where you come in.", "Daniel")
    story.printCharacterText("Your job is to go around and ask the others questions and try to get evidence agains Alex.", "Daniel")
    story.printCharacterText("Go ask around and try to find Alex. I've got some things I need to do.", "Daniel")
    story.showPlayerChoices("Ask Will", "Ask Ruby", "Ask Louis")
    // This is a fork in the story that hopefully sways the players choice on the imposter at the end.
    if (story.checkLastAnswer("Ask Will")) {
        story.printCharacterText("Ok. Go see if will has noticed anything while you're there", "Daniel")
        Active_talker_set_Will()
        story.printCharacterText("Hey Rookie. What's up?", "Will")
        story.showPlayerChoices("Have you seen Alex?", "Who do you think the imposter is?")
        if (story.checkLastAnswer("Who do you think the imposter is?")) {
            story.printCharacterText("Honestly, ever since Alex showed up Daniel's been...", "Will")
            story.printCharacterText("Off...", "Will")
            story.printCharacterText("I- Well, I me- It's kinda hard to explain.", "Will")
            story.printCharacterText("He used to have this 'Flair' of sorts.", "Will")
            story.printCharacterText("I know it seems stupid, But he also seems luckier if that makes sense.", "Will")
            story.showPlayerChoices("How so?", "No, that makes a little sense.")
            if (story.checkLastAnswer("How so?")) {
                story.printCharacterText("He used to kind of have an omen I guess.", "Will")
                story.printCharacterText("During important moments, usually comedically bad thing would happen to him. ", "Will")
                story.printCharacterText("There was this one time where we were fending off a hoard of infected", "Will")
                story.printCharacterText("And in the middle of the battle,", "Will")
                story.printCharacterText("A.C.E told us all that Daniel had 5 seconds before his armour shut down for,", "Will")
                story.printCharacterText("I kid you not...", "Will")
                story.printCharacterText("A windows update.", "Will")
            }
            story.printCharacterText("Yeah. Basically, he seems luckier.", "Will")
            story.printCharacterText("Something else seems off as well, but I can't quite put my finger on it...", "Will")
            story.printCharacterText("Is there anything else you need?", "Will")
            Active_talker_set_Rookie()
            story.printCharacterText("Yeah, have you seen Alex at all?", UserName)
        }
        Active_talker_set_Will()
        story.printCharacterText("Yeah, he's just down the hall, to the left", "Will")
        story.printCharacterText("There will be a couple of rooms, he'll be in the one with a symbol of a bomb.", "Will")
    } else if (story.checkLastAnswer("Ask Ruby")) {
        story.printCharacterText("Alright, Go get 'em.", "Daniel")
        Active_talker_set_Ruby()
        story.printCharacterText("" + UserName + "! Whatcha need?", "Ruby")
        story.showPlayerChoices("I need to find Alex", "What are your thoughts on the spy?")
        if (story.checkLastAnswer("What are your thoughts on the spy?")) {
            Active_talker_set_Ruby()
            story.printCharacterText("Unfortunately...", "Ruby")
            story.printCharacterText("I think it's Louis.", "Ruby")
            story.printCharacterText("Ever since Alex showed up, he's gotten angrier, easier.", "Ruby")
            story.printCharacterText("And I'd rather leave it at that.", "Ruby")
            story.printCharacterText("Also, If you're looking for Alex,", "Ruby")
        }
        story.printCharacterText("He's down the hall in the room that has a bomb on the door.", "Ruby")
    } else if (story.checkLastAnswer("Ask Louis")) {
        story.printCharacterText("Yeah, Louis might know where you can find Alex.", "Daniel")
        Active_talker_set_Louis()
        story.printCharacterText("Hey. How's it going?", "Louis")
        story.showPlayerChoices("Do you know where Alex is?", "Who do you think the mole is?")
        if (story.checkLastAnswer("Who do you think the mole is?")) {
            story.printCharacterText("Alex.", "Louis")
            story.printCharacterText("I have no doubt.", "Louis")
            story.printCharacterText("And let's not go any further than that question.", "Louis")
            story.printCharacterText("If you're looking for him,", "Louis")
        }
        story.printCharacterText("He's over at the barracks. There'll be a door with a bomb on it. He'll be in there.", "Louis")
    }
    Active_talker_set_Alex()
    story.printCharacterText("Hey.", "Alex")
    story.showPlayerChoices("Hey", "Who do you think the boogey is?")
    if (story.checkLastAnswer("Who do you think the boogey is?")) {
        story.printCharacterText("Honestly...", "Alex")
        story.printCharacterText("I'm not sure", "Alex")
        Active_talker_set_Rookie()
        story.printCharacterText("a lot of people think it's you", UserName)
    }
    Active_talker_set_Alex()
    story.printCharacterText("Hmm.", "Alex")
    story.printCharacterText("Actually, follow me.", "Alex")
    story.showPlayerChoices("*stay quiet*", "Where are we going?")
    if (story.checkLastAnswer("Where are we going?")) {
        story.printCharacterText("To find answers.", "Alex")
    }
    game.splash("The Database", "Space to continue")
    story.printCharacterText("Here.", "Alex")
    story.printCharacterText("This is where the Dossier is held.", "Alex")
    Active_talker_set_Rookie()
    story.printCharacterText("What's the Dossier?", UserName)
    Active_talker_set_Alex()
    story.printCharacterText("The Dossier is an archive of everything recorded by the UNPD.", "Alex")
    story.printCharacterText("Including info on everyone on our team.", "Alex")
    story.printCharacterText("This will hopefully help us find who the imposter is.", "Alex")
    story.printCharacterText("But we only have time to search 1 Bio, so look into who you think the Boogey is.", "Alex")
    story.printCharacterText("Daniel's just requested we all meet him at the briefing room", "Alex")
    story.printCharacterText("Alright, who are we choosing?", "Alex")
    story.showPlayerChoices("Search Daniel", "Search Will", "Search Ruby", "Search Louis")
    if (story.checkLastAnswer("Search Daniel")) {
        Active_talker_set_Rookie()
        story.printCharacterText("Ok...", UserName)
        story.printCharacterText("It says here that Daniel has a blue nametag on the right part of his chest plate.", UserName)
        story.printCharacterText("His Reactor is a blue hexagon in the middle of his chest.", UserName)
        Active_talker_set_Alex()
        story.printCharacterText("Is there anything else?", "Alex")
        Active_talker_set_Rookie()
        story.printCharacterText("It says here he was born in Yorkshire, England", UserName)
        Active_talker_set_Alex()
        story.printCharacterText("Ok, we gotta go.", "Alex")
    } else if (story.checkLastAnswer("Search Will")) {
        Active_talker_set_Rookie()
        story.printCharacterText("Alright.", UserName)
        story.printCharacterText("Will, Will, Will...", UserName)
        story.printCharacterText("Will has a modified visor attachment that improves his accuracy and sight drastically.", UserName)
        story.printCharacterText("His reactor is a green diamond on his chest plate.", UserName)
        Active_talker_set_Alex()
        story.printCharacterText("That all?", "Alex")
        Active_talker_set_Rookie()
        story.printCharacterText("He was also born in Austin, Texas in the United States.", UserName)
        Active_talker_set_Alex()
        story.printCharacterText("Ok. That's all we can do. Daniel wants us up there now.", "Alex")
    } else if (story.checkLastAnswer("Search Ruby")) {
        Active_talker_set_Rookie()
        story.printCharacterText("Alright Ruby, Let's see what you're hiding...", UserName)
        story.printCharacterText("Ruby's got a red circular reactor in the middle of her chest piece.", UserName)
        story.printCharacterText(" and a set of thruster jets hidden behind the plating on the back of her calves", UserName)
        Active_talker_set_Alex()
        story.printCharacterText("Well that doesn't help. we are in a game where we can't even see our legs. ", "Alex")
        story.printCharacterText("In fact, I didn't even know we had any", "Alex")
        story.printCharacterText("What else can you find?", "Alex")
        Active_talker_set_Rookie()
        story.printCharacterText("Umm...", UserName)
        story.printCharacterText("She was born in Alice Springs, Australia", UserName)
        Active_talker_set_Alex()
        story.printCharacterText("That's all we have time for. We've gotta go to that meeting.", "Alex")
    } else if (story.checkLastAnswer("Search Louis")) {
        Active_talker_set_Rookie()
        story.printCharacterText("Louis. The only non-PG character here. That's gotta mean something.", UserName)
        story.printCharacterText("His reactor in the middle of his chest plate is a yellow square.", UserName)
        story.printCharacterText("And he was born in cape town in South Africa.", UserName)
        Active_talker_set_Alex()
        story.printCharacterText("Hey. Daniel's calling us up to the meeting room. We need to go now.", "Alex")
    }
    game.splash("The Meeting", "Space to continue")
    Active_talker_set_Disguised_Daniel()
    story.printCharacterText("Ok.", "Daniel")
    story.printCharacterText("Command has told me that getting the Boogey of the team is a top priority.", "Daniel")
    story.printCharacterText("And that we need to get it done at any cost.", "Daniel")
    story.printCharacterText("Even if that means getting rid of one of us right now...", "Daniel")
    story.printCharacterText("I have had " + UserName + " go around and investigate you lot.", "Daniel")
    story.printCharacterText("And I believe he has found who the Boogey is.", "Daniel")
    story.printCharacterText("" + UserName + " is going to tell us who the imposter is, and we will then have them removed from the team.", "Daniel")
    story.printCharacterText("Ok, " + UserName + ". Who's the Boogey", "Daniel")
    story.showPlayerChoices("Daniel", "Will", "Ruby", "Louis")
    if (story.checkLastAnswer("Daniel")) {
        Active_talker_set_Disguised_Daniel()
        story.printCharacterText("What?!", "Daniel")
        story.printCharacterText("Why me?!", "Daniel")
        Active_talker_set_Will()
        story.printCharacterText("Sorry man. Gotta agree with the Rookie on this one.", "Will")
        Active_talker_set_Ruby()
        story.printCharacterText("What? He's our Leader?", "Ruby")
        Active_talker_set_Louis()
        story.printCharacterText("And he's been with us since the start.", "Louis")
        story.printCharacterText("In fact, he was the first Bushranger.", "Louis")
        Active_talker_set_Will()
        story.printCharacterText("Yeah, It's just...", "Will")
        story.printCharacterText("Something's off...", "Will")
        Active_talker_set_Ruby()
        story.printCharacterText("The hell's that supposed to mean?!", "Ruby")
        Active_talker_clear()
        story.printCharacterText("HMMM!", "???")
        Active_talker_set_Louis()
        story.printCharacterText("Uhhhh. Wha-", "Louis")
        Active_talker_clear()
        story.printCharacterText("HHMPHHMM! HMMMPH!", "???")
        Active_talker_set_Disguised_Daniel()
        story.printCharacterText("Oh no...", "Daniel?")
        Active_talker_clear()
        story.printCharacterText("IT'S NOT ME!", "???")
        Active_talker_set_Alex()
        story.printCharacterText("It's coming from over there!", "Alex")
        Active_talker_set_Kidnapped_Daniel()
        story.printCharacterText("Guys!", "???")
        story.printCharacterText("It's Me! Daniel!", "???")
        story.printCharacterText("Get me outa here!", "Daniel")
        Active_talker_set_Alex()
        story.printCharacterText("Ruby, Get the bag off his head.", "Alex")
        Active_talker_set_Beat_Up_Daniel()
        story.printCharacterText("Ah!", "Daniel")
        story.printCharacterText("Guys! It's me!", "Daniel")
        Active_talker_set_Louis()
        story.printCharacterText("Woah! What happened to you?", "Daniel")
        Active_talker_set_Beat_Up_Daniel()
        story.printCharacterText("I can't remember...", "Daniel")
        story.printCharacterText("But that... Thing.", "Daniel")
        story.printCharacterText("It's not me...", "Daniel")
        Active_talker_set_Daniel_Grain()
        story.printCharacterText("Hmm. Wondered if any of you would figure it out.", "Evil Daniel")
        story.printCharacterText("Turns out, of all of you. It was the Rookie that caught me.", "Evil Daniel")
        Active_talker_set_Will()
        story.printCharacterText("psst. Daniel.", "Will")
        story.printCharacterText("Here's your helmet. It's a little banged up, but we can fix itlater.", "Will")
        Active_talker_set_Battle_damaged_Daniel()
        story.printCharacterText("Thanks.", "Daniel")
        story.printCharacterText("Hey, you must be the Rookie.", "Daniel")
        Active_talker_set_Rookie()
        story.printCharacterText("Yes sir.", UserName)
        Active_talker_set_Battle_damaged_Daniel()
        story.printCharacterText("Don't worry about the formalities. Just call me Daniel.", "Daniel")
        Active_talker_set_Ruby()
        story.printCharacterText("Hate to break up the introduction, But where'd that 'thing' go?", "Daniel")
        Active_talker_set_Battle_damaged_Daniel()
        story.printCharacterText("Goddamn it.", "Daniel")
    } else if (story.checkLastAnswer("Will")) {
        Active_talker_set_Will()
        story.printCharacterText("What?", "Will")
        story.printCharacterText("I don't- wha- How? Why?", "Will")
        story.printCharacterText("It's not me!", "Will")
        Active_talker_set_Disguised_Daniel()
        story.printCharacterText("Look, I wish it wasn't you, but the Rookie did his investigating.", "Daniel")
        story.printCharacterText("The Evidence doesn't lie.", "Daniel")
        Active_talker_set_Louis()
        story.printCharacterText("Are we sure It's Will?", "Louis")
        Active_talker_set_Rookie()
        story.printCharacterText("Yeah.", UserName)
        story.printCharacterText("It all matches up.", UserName)
        Active_talker_set_Will()
        story.printCharacterText("*sigh*", "Will")
        story.printCharacterText("I understand.", "Will")
        story.printCharacterText("I just want you all to know...", "Will")
        story.printCharacterText("I guarentee you I'm not the boogey.", "Will")
        Active_talker_clear()
        game.splash("1 Week Later", "Space to continue")
        Active_talker_set_Alex()
        story.printCharacterText("Hey.", "Alex")
        Active_talker_set_Rookie()
        story.printCharacterText("What if it wasn't him?", UserName)
        Active_talker_set_Alex()
        story.printCharacterText("Don't think like that.", "Alex")
        story.printCharacterText("You did all you could.", "Alex")
        Active_talker_clear()
        pause(100)
        Active_talker_set_Alex()
        pause(100)
        Active_talker_clear()
        pause(500)
        Active_talker_clear()
        story.printCharacterText("Ummm.", "Alex")
        story.printCharacterText("Who turned the lights off?", "Alex")
        story.printCharacterText("Ummm. Guys?", "Ruby")
        story.printCharacterText("You might want to come and see this!", "Ruby")
        story.printCharacterText("What is it?", "Alex")
        story.printCharacterText("Has anyone got a torch?", "Alex")
        story.printCharacterText("Yeah, here.", "Louis")
        Active_talker_set_Dead_daneil()
        story.printCharacterText("Oh no...", "Ruby")
        story.printCharacterText("Oooohhhh.", "Louis")
        story.printCharacterText("Yeah, He's dead...", "Louis")
        Active_talker_set_Alex()
        story.printCharacterText("I take it back Rookie. I don't think we got him...", "Alex")
        Active_talker_set_Rookie()
        story.printCharacterText("This means, He's still here.", UserName)
        Active_talker_set_Ruby()
        story.printCharacterText("Uh oh.", "Ruby")
        Active_talker_set_Louis()
        story.printCharacterText("What?", "Louis")
        Active_talker_set_Ruby()
        story.printCharacterText("All appliances are disconnected. Nothing has power.", "Ruby")
        Active_talker_set_Alex()
        story.printCharacterText("You don't say.", "Alex")
        Active_talker_set_Ruby()
        story.printCharacterText("I mean everything. Doors included.", "Ruby")
        story.printCharacterText("We're stuck in here...", "Ruby")
        Active_talker_set_Louis()
        story.printCharacterText("I think this might be an appropriate time.", "Louis")
        Active_talker_set_Ruby()
        story.printCharacterText("For what?", "Ruby")
        Active_talker_set_Rookie()
        story.printCharacterText("A Son of a Bitch moment.", UserName)
        Active_talker_set_Louis()
        story.printCharacterText("Exactly. A very big Son of a Bitch moment.", "Louis")
        Active_talker_clear()
        story.printCharacterText("Ohh. This is definately a Son of a Bitch moment.", "???")
        story.printCharacterText("Son of a Bitch.", "Louis")
        story.printCharacterText("Enough sons of a bitches!", "Ruby")
        story.printCharacterText("You just said it.", "Louis")
        story.printCharacterText("Oh shut up.", "Ruby")
    } else if (story.checkLastAnswer("Ruby")) {
        Active_talker_set_Ruby()
        story.printCharacterText("No!", "Ruby")
        story.printCharacterText("Bullshit!", "Ruby")
        story.printCharacterText("What evidence do you have?!", "Ruby")
        Active_talker_set_Louis()
        story.printCharacterText("He's clearly got enough to blame you!", "Louis")
        Active_talker_set_Ruby()
        story.printCharacterText("Well I don't know what their source is. Because I'm not the Boogey.", "Ruby")
        story.printCharacterText("If anything it's you.", "Ruby")
        Active_talker_set_Louis()
        story.printCharacterText("F#CK OFF!", "Louis")
        Active_talker_set_Ruby()
        story.printCharacterText("What?! You're the one who started to get mad when Alex showed up!", "Ruby")
        Active_talker_set_Disguised_Daniel()
        story.printCharacterText("Louis, Put the gun down.", "Daniel")
        Active_talker_set_Louis()
        story.printCharacterText("Make me.", "Louis")
        Active_talker_set_Disguised_Daniel()
        story.printCharacterText("LOUIS! PUT THE GUN DOW-", "Daniel")
        Active_talker_set_Ruby()
        scene.cameraShake(4, 100)
        story.printCharacterText("*Ruby shoots Louis in the head*")
        story.printCharacterText("Done.", "Ruby")
        Active_talker_set_Disguised_Daniel()
        story.printCharacterText("Ok...", "Daniel")
        story.printCharacterText("Let's all calm down.", "Daniel")
        story.printCharacterText("Holster our guns.", "Daniel")
        story.printCharacterText("And hope Ruby just killed the Boogey.", "Daniel")
        Active_talker_set_Rookie()
        story.printCharacterText("Are we going to need to replace him?", UserName)
        Active_talker_set_Disguised_Daniel()
        story.printCharacterText("I...", "Daniel")
        story.printCharacterText("Don't know.", "Daniel")
    } else if (story.checkLastAnswer("Louis")) {
        Active_talker_set_Louis()
        story.printCharacterText("Yeah? well F#ck you too.", "Louis")
        story.printCharacterText("I can't believe you've actually listened to him, you idiot.", "Louis")
        Active_talker_set_Rookie()
        story.printCharacterText("What do you mean?", UserName)
        Active_talker_set_Louis()
        story.printCharacterText("Couldn't you tell? Why do you think Alex tried to kill me earlier?", "Louis")
        story.printCharacterText("He's been trying to destroy this facility since he got here.", "Louis")
        Active_talker_set_Alex()
        story.printCharacterText("Nuh Uh.", "Alex")
        story.printCharacterText("Command ordered me to set up a failsafe for if the Boogey takes over the facility.", "Alex")
        Active_talker_set_Louis()
        story.printCharacterText("Yeah,", "Louis")
        story.printCharacterText("and command told me to set up 2 metric tonnes of explosives to blow your ass sky high if you try anything. ", "Louis")
        Active_talker_set_Alex()
        story.printCharacterText("You wouldn't.", "Alex")
        Active_talker_set_Louis()
        story.printCharacterText("You really want to gamble your life on a guess?", "Louis")
        Active_talker_set_Alex()
        story.printCharacterText("Don't have to because I ha-", "Alex")
        Active_talker_set_Louis()
        scene.cameraShake(4, 500)
        story.printCharacterText("BOOM!")
        Active_talker_set_Will()
        story.printCharacterText("Woah! What have you done?!", "Will")
        Active_talker_set_Louis()
        story.printCharacterText("He had a primed grenade in his hand. He was about to kill us all!", "Louis")
        Active_talker_set_Disguised_Daniel()
        story.printCharacterText("That didn't give you the clearance to kill him!", "Daniel")
        Active_talker_set_Louis()
        story.printCharacterText("It was either I kill him, or he was going to kill us!", "Louis")
        Active_talker_set_Rookie()
        story.printCharacterText("Hey. Did any of you lock the doors?", UserName)
        Active_talker_clear()
        story.printCharacterText("Yeah. That would be me...", "???")
    }
}
Active_talker_clear()
i = textsprite.create("Thanks for Playing!")
i.setPosition(90, 59)
